name: example
description: "A Flutter project to demonstrate the use of the magic_the_gathering_flutter package."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  magic_the_gathering_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
